# 02 Black Scholes game.

Explain changes in the price of the option due to changes in the underlying parameters.

In [ ]:
import numpy as np

from shapley_numba.common import subsets
from shapley_numba.examples.finance import BlackScholesCallGame
from shapley_numba.harsanyi_naive import harsanyi_dividends
from shapley_numba.shapley import shapley

In [2]:
game = BlackScholesCallGame(
    old_parameters=np.array([100, 1, 0.05, 0.2]),
    new_parameters=np.array([105, 0.75, 0.055, 0.25]),
    strike=110.0,
)

In [3]:
old_value = game.value(np.array([0, 0, 0, 0]))
new_value = game.value(np.array([1, 1, 1, 1]))
print('old value', old_value)
print('new value', new_value)
print('Change to explain', new_value - old_value)

old value 6.040088129724225
new value 8.800724823107544
Change to explain 2.7606366933833186


In [4]:
shapley(game, 4)

array([ 2.46650459, -1.78811388,  0.18826859,  1.89397739])

In [5]:
for subset in subsets(4):
    print(subset, harsanyi_dividends(game, subset))

[0 0 0 0] 6.040088129724225
[1 0 0 0] 2.492871284992276
[0 1 0 0] -1.5180748448761108
[1 1 0 0] -0.20158700033770316
[0 0 1 0] 0.19660963982492063
[1 0 1 0] 0.04974116206298618
[0 1 1 0] -0.06135005304311392
[1 1 1 0] -0.006887445129201808
[0 0 0 1] 1.9862965641291268
[1 0 0 1] 0.0910151216318198
[0 1 0 1] -0.2937219201339829
[1 1 0 1] 0.02782502367695372
[0 0 1 1] 0.0035390589919401805
[1 0 1 1] -0.009964729363701963
[0 1 1 1] 0.0027606583400370255
[1 1 1 1] 0.0015641726170727566
